resolves #1088: fix log messages (#1113)
* refactor/active_conn: remove redundant error handling

Heartbeat constructor never failed, so returning result instead of
Heartbeat resulted in redundant error handling.

* fix/log_messages: fixed log levels

Changed log levels according to such logic

trace; very low priority, often extremely verbose, information.
debug: lower priority information.
info:  more serious/useful information.
warn:  something unexpected happened and we should have terminated the
       entire process, but are not in the hope that some parts might still
       continue to work correctly, but the behaviour after this might be
       undefined.
error: when you are terminating the process.

* docs/service: document service architecture